WebAppMVC/Models/Assignment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppMVC.Models
{
    public class Assignment
    {
        public int AssignmentID { get; set; }
        public int EmployeeID { get; set; }
        public int CustomerID { get; set; }

        public string Description { get; set; }
        //[DataType(DataType.Date)]
        public DateTime Date { get; set; }
        //[Column(TypeName = "decimal(4, 2)")]
        public decimal StartTime { get; set; }
        //[Column(TypeName = "decimal(4, 2)")]
        public decimal EndTime { get; set; }
        //[Column(TypeName = "decimal(4, 2)")]
        //[Display(Name = "Number of Hours")]
        public decimal HoursAmount { get; set; }
        //[Column(TypeName = "decimal(18, 2)")]
        public decimal OB1 { get; set; }
        //[Column(TypeName = "decimal(18, 2)")]
        public decimal OB2 { get; set; }
        public string Karens { get; set; }
        public string SickLeave { get; set; }
        public string VAB { get; set; }
        public string Vacation { get; set; }
        //[Display(Name = "Vacation Compensation")]
        //[Column(TypeName = "decimal(18, 2)")]
        public decimal VacationCompensation { get; set; }
        //[Column(TypeName = "decimal(18, 2)")]
        //[Display(Name = "Extra Cost")]
        public decimal ExtraCost { get; set; }
        public string GPSLocation { get; set; }

        public Customer Customer { get; set; }
        public Employee Employee { get; set; }
    }
}

WebAppMVC/Controllers/AssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Net.Mail;
using System.Net.Mime;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using WebAppMVC.Models;
using System.IO;
using System.Text;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using System.Drawing;



namespace WebAppMVC.Controllers
{

    public class AssignmentsController : Controller
    {

        private DBContext db = new DBContext();

        public string email { get; set; }
        public string password { get; set; }
        public string workhours { get; set; }
        public string hourly { get; set; }
        public string total { get; set; }
        public string employeename { get; set; }
        public string timeperiod { get; set; }
        public string timeperiod_title { get; set; }
        public string startmonth = "0";
        public string startyear = "0";
        public List<string> emptotalhours { get; set; }

        // GET: Assignments - Show All Assignments
        public ActionResult Index()
        {           
            var assignment = db.Assignment.Include(a => a.Customer).Include(a => a.Employee);
            return View(assignment.ToList());
        }

        
        // GET: Assignments - Show Assignment for specific Employee - Assignments?id=1 .. 
        public ActionResult EmployeeIndex(int? id)
        {
            var assignment = db.Assignment.Include(a => a.Customer).Include(a => a.Employee).Where(a => a.EmployeeID == id);
            return View(assignment.ToList());
        }

        public IList<Assignment> hours { get; set; }

        // GET: Assignments - Show All WorkHours per Month per Employee ..
        public ActionResult WorkHours()
        {
            // ## Antal arbetade timmar för alla anställda för en viss månad - Kanske "CARDS" som FrontEnd

            if (Request["Year"] != null)
            {
                startyear = Request["Year"];
            }
            else
            {
                startyear = "2019";
            }

            if (Request["Month"] != null)
            {
                startmonth = Request["Month"];
            }
            else
            {
                startmonth = "1";
            }

            int intyear = Convert.ToInt32(startyear);
            int intmonth = Convert.ToInt32(startmonth);
            int days = DateTime.DaysInMonth(intyear, intmonth);

            ViewBag.startyear = startyear;
            ViewBag.startmonth = startmonth;

            string d = startyear + "-" + startmonth + "-01 00:00:00";
            DateTime startdate = Convert.ToDateTime(d);

            string d2 = startyear + "-" + startmonth + "-" + days.ToString() + " 00:00:00";

            DateTime enddate = Convert.ToDateTime(d2);

            ViewBag.timeperiod_title += "Timeperiod: " + startdate + " - " + enddate + " ";

            decimal TotalHours = 0;
            decimal TotalSalary = 0;
            decimal HourlyPay = 0;
            string Name = "";

            //

            hours = db.Assignment.Include(a => a.Customer).Include(a => a.Employee).Where(a => a.Date >= startdate).Where(a => a.Date <= enddate).OrderBy(a => a.EmployeeID).ToList();

            int x = 0;
            foreach (var el in hours)
            {
                if (x == 0)
                {
                    Name = el.Employee.FirstName + " " + el.Employee.LastName;
                    x = 1;
                }
                if (Name == el.Employee.FirstName + " " + el.Employee.LastName)
                {
                    // Same employee                  
                    TotalHours += el.HoursAmount;

                }
                else
                {
                    // Write the first line out from Employee TotalHours

                    ViewBag.emptotalhours += "Name: " + Name + " Total workhours: " + TotalHours + " ";
                    ViewBag.emptotalhours += "-----------------------------------------------------------------";
                    ViewBag.emptotalhours += "-----------------------------------------------------------------";
                    ViewBag.emptotalhours += "-----------------------------------------------------";

                    TotalHours = 0;
                    TotalHours += el.HoursAmount;

                    // New employee
                    Name = el.Employee.FirstName + " " + el.Employee.LastName;
                }

            }
            ViewBag.emptotalhours += "Name: " + Name + " Total workhours: " + TotalHours;
            ViewBag.emptotalhours += "-----------------------------------------------------------------";
            ViewBag.emptotalhours += "-----------------------------------------------------------------";
            ViewBag.emptotalhours += "-----------------------------------------------------";

            return View(hours);
        }

        public IList<Assignment> salary { get; set; }

        // Temporary action for Sending the Pdf Email

        // GET: Assignments - Show Salary Sum per Month for specific Employee - Assignments?id=1 .. 
        public ActionResult SalaryEmployee(int? id)
        {
            // List all hours - add and deduct special cost --
            // SP - add per row then sum it up - then taxes ..

            //var ID = Request.Cookies["sitecookies"]["Email"].ToString();
            //var id = Convert.ToInt32(ID);

            if (Request["Year"] != null)
            {
                startyear = Request["Year"];
            }
            else
            {
                startyear = "2019";
            }

            if (Request["Month"] != null)
            {
                startmonth = Request["Month"];
            }
            else
            {
                startmonth = "1";
            }

            int intyear = Convert.ToInt32(startyear);
            int intmonth = Convert.ToInt32(startmonth);
            int days = DateTime.DaysInMonth(intyear, intmonth);

            ViewBag.startyear = startyear;
            ViewBag.startmonth = startmonth;

            string d = startyear + "-" + startmonth + "-01 00:00:00";
            DateTime startdate = Convert.ToDateTime(d);

            string d2 = startyear + "-" + startmonth + "-" + days.ToString() + " 00:00:00";

            DateTime enddate = Convert.ToDateTime(d2);

            decimal TotalHours = 0;
            decimal TotalSalary = 0;
            decimal HourlyPay = 0;
            string Name = "";
            string Emailto = "";

            salary = db.Assignment.Include(a => a.Customer).Include(a => a.Employee).Where(a => a.EmployeeID == id).Where(a => a.Date >= startdate).Where(a => a.Date <= enddate).ToList();

            foreach (var el in salary)
            {
                ViewBag.workhours += el.HoursAmount + " * " + el.Employee.HourlySalary + " <br> ";

                TotalHours += el.HoursAmount;

                HourlyPay = el.Employee.HourlySalary;
                Name = el.Employee.FirstName + " " + el.Employee.LastName;
                Emailto = el.Employee.Email;

                if (el.OB1 != 0)
                {
                }
            }
            TotalSalary = TotalHours * HourlyPay;

            ViewBag.employeename = Name;
            ViewBag.timeperiod = "Timeperiod: " + startdate + " - " + enddate;
            ViewBag.hourly = "Hourly Salary: " + HourlyPay + " SEK";
            ViewBag.workhours = "Total Hours: " + TotalHours + " Hours";
            ViewBag.total = "Total Salary: " + TotalSalary + "  ";

            if (Request["SendEmail"] == "Yes")
            {
                using (PdfDocument document = new PdfDocument())
                {
                    string body = "From: SwipeIT Inc. \n\n" +
                    "Current Salary Receipt. \n\n" +
                    "Employeename: " + Name + "\n\n" + "Timeperiod: " + startdate.ToString() + " - " + enddate.ToString() + "\n\n" +
                    "Hourly Salary: " + HourlyPay.ToString() + "\t" + "Total Hours: " + TotalHours.ToString() +
                    "\n\n" + "Total Salary: " + TotalSalary.ToString() + "\n\n" +
                    "Regards \nSwipeIT Inc. ";

                    //Add a page to the document
                    PdfPage page = document.Pages.Add();

                    //Create PDF graphics for the page
                    PdfGraphics graphics = page.Graphics;

                    //Set the standard font
                    PdfFont font = new PdfStandardFont(PdfFontFamily.Helvetica, 20);

                    //Draw the text
                    graphics.DrawString(body, font, PdfBrushes.Black, new PointF(0, 0));

                    // Open the document in browser after saving it
                    document.Save("SalaryReceipt.pdf", HttpContext.ApplicationInstance.Response, HttpReadType.Save);

                }

            }

            if (Request["SendEmail"] != null)
            {
                if (Request["SendEmail"] == "Yes")
                {

                    // Use my own email-address for Testing, not DB Email, read Code above => 
                    // Comment out after Testing, the Row below =>
                    
                    Emailto = "receiver@gmail.com";

                    var body = "From: SwipeIT Inc. \n\n" +
                    "Current Salary Receipt. \n\n" +
                    "Employeename: " + Name + "\n\n" + "Timeperiod: " + startdate + " - " + enddate + "\n\n" +
                    "Hourly Salary: " + HourlyPay + "\t" + "Total Hours: " + TotalHours + "\n\n" +
                    "Total Salary: " + TotalSalary + "\n\n" +
                    "Regards \nSwipeIT Inc. ";

                    string To = Emailto;
                    string From = "sender@hotmail.com";
                    string Subject = "Salary Receipt";
                    string Body = string.Format(body);

WebAppMVC/Views/Assignments/Delete.cshtml
@model WebAppMVC.Models.Assignment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoursAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoursAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OB1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OB1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OB2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OB2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Karens)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Karens)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SickLeave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SickLeave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VAB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VAB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vacation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vacation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VacationCompensation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VacationCompensation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtraCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtraCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GPSLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GPSLocation)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebAppMVC/Views/Assignments/EmployeeCreate.cshtml
@model WebAppMVC.Models.Assignment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Assignment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeID, "EmployeeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoursAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                The Total amount of Hours you have worked<br />
                @Html.EditorFor(model => model.HoursAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoursAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OB1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                Monday-Friday 20.00 - 01.00, Saturday 16.00 - 01.00, Sunday 06.00 - 01.00<br />
                @Html.EditorFor(model => model.OB1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OB1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OB2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                Nigths 01.00 - 06.00<br />
                @Html.EditorFor(model => model.OB2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OB2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Karens, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Karens, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Karens, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SickLeave, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SickLeave, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SickLeave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VAB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VAB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VAB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vacation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vacation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vacation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VacationCompensation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VacationCompensation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VacationCompensation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExtraCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExtraCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExtraCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GPSLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GPSLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GPSLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @{
            if (HttpContext.Current.Request.Cookies["sitecookies"] != null)
            {
                var ID = Request.Cookies["sitecookies"]["Email"].ToString();
                var emp_id = Convert.ToInt32(ID);
                @Html.ActionLink("Back to List", "EmployeeIndex/" + emp_id, "Assignments")
            }
        }
    </div>

WebAppMVC/Views/Assignments/EmployeeDelete.cshtml
@model WebAppMVC.Models.Assignment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoursAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoursAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OB1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OB1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OB2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OB2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Karens)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Karens)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SickLeave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SickLeave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VAB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VAB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vacation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vacation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VacationCompensation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VacationCompensation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtraCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtraCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GPSLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GPSLocation)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="EmployeeDelete" class="btn btn-default" /> |
        
        @{
            if (HttpContext.Current.Request.Cookies["sitecookies"] != null)
            {
                var ID = Request.Cookies["sitecookies"]["Email"].ToString();
                var emp_id = Convert.ToInt32(ID);
                @Html.ActionLink("Back to List", "EmployeeIndex/" + emp_id, "Assignments")
            }
        }
    </div>
    }
</div>

WebAppMVC/Views/Assignments/EmployeeDetails.cshtml
@model WebAppMVC.Models.Assignment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoursAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoursAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OB1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OB1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OB2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OB2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Karens)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Karens)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SickLeave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SickLeave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VAB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VAB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vacation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vacation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VacationCompensation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VacationCompensation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtraCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtraCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GPSLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GPSLocation)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EmployeeEdit", new { id = Model.AssignmentID }) |

    @{
        if (HttpContext.Current.Request.Cookies["sitecookies"] != null)
        {
            var ID = Request.Cookies["sitecookies"]["Email"].ToString();
            var emp_id = Convert.ToInt32(ID);
            @Html.ActionLink("Back to List", "EmployeeIndex/" + emp_id, "Assignments")
        }
    }
</p>